### ISSUE TITLE
edk2 and NanoPC-T6

### ISSUE THREAD

**Issue by brightplastik** [edk2-porting/edk2-rk3588#120]
Hello geeks! First of all congratuation for this amazing work. The SBCs are now to be considered a 100% power sipping computers, thans to your porting of a UEFI env.
I soldered a NOR chip on my board and flashed it with edk2 0.9.1
Then I tried installing both Jangcuo's Proxmox port and amazingfate's legacy kernel debian ISO, and I got the same results: black screen and no peripherals.
Then I downgraded to edk2 0.8, following amazingfate's suggestion, and boom, it worked. I think it has to do with the injection of DTB and overlays you introduced in ver. 0.9 and over.
So then I tried to add /dtb/base and /dtb/overlays to the root of the installers (as you say [in the wiki](https://github.com/edk2-porting/edk2-rk3588/blob/v0.9.1/README.md#custom-device-tree-blob-dtb-override-and-overlays)), copying them from amazingfate's iso, but it didn't work unfortunately.

Could you please explain to this noob how to manipulate the installers of the operating systems in order to properly boot them?
It would be of immense help, and allow me to finally install a copy of [proxmox-port](https://mirrors.apqa.cn/proxmox/isos/) on this board. This is what I'm looking for, in the end.

My best regards to you,
Gabriel

**Comment by mariobalanica** [comment]
DTB support is disabled by default in favor of ACPI. I don't believe Proxmox would even work with DTB unless you're using the Rockchip legacy kernel.

> and I got the same results: black screen and no peripherals

When exactly does this happen? Do you see the UEFI boot screen at least?

**Comment by brightplastik** [comment]
After many more attempts, now this is everything I achieve:
![IMG_20240202_141331.jpg](https://github.com/edk2-porting/edk2-rk3588/assets/45295288/ba88ffb9-2472-4a8e-a451-b891c9e47d47)
And after this:
![IMG_20240202_141153.jpg](https://github.com/edk2-porting/edk2-rk3588/assets/45295288/af538f25-c0b9-4456-9cb3-3a93d7e60b7a)

**Comment by mariobalanica** [comment]
[Serial logs](https://github.com/edk2-porting/edk2-rk3588?tab=readme-ov-file#advanced-troubleshooting) would be helpful here.

The display output doesn't say much, but it appears to not find the storage drive. Note that only USB, NVME and SATA are usable with Linux.

**Comment by brightplastik** [comment]
I downloaded [this file](https://github.com/edk2-porting/edk2-rk3588/actions/runs/7590733798/artifacts/1182417129) that I think is your last commit. 
ASAP I will post the log.
Thank you Mario! I appreciate your help!

**Comment by brightplastik** [comment]
Ok, so time for a recap.
Upgraded from 0.8 to one of your your last debug artifact, as posted above.
Same settings in the GUI as 0.8 (ACPI only, no override allowed), but I never get to boot my Debian installation from amazingfate on the eMMC.
Logs of bootup with nightly debug are [here](https://pastebin.com/Lb3m7vd2)

With 0.8 I can bootup no problem. Unfortunately I don't have a debug copy of 0.8, so I cannot show what is the difference.

**Comment by mariobalanica** [comment]
Ah, v0.9 changed the DTB name reported in SMBIOS and amazingfate's Armbian doesn't account for that, so it fails to load any DTB. Their kernel is not compiled with ACPI support either.

You need to enable Device Tree mode as described here: https://github.com/edk2-porting/edk2-rk3588?tab=readme-ov-file#device-tree-configuration

As for Proxmox, I have no idea.

**Comment by brightplastik** [comment]
@mariobalanica as usual, thanks a lot for your presence.
I'm quite sure I selected device tree in settings, with no override, to no avail unfortunately.
I'll try again, as a working install of Debian might suffice, as long as it plays nicely with your edk2 porting.
I will report back, with debug logs.
🙏🙏🙏🙏🙏🙏

**Comment by brightplastik** [comment]
@mariobalanica as usual, thanks a lot for your presence.
I'm quite sure I selected device tree in settings, with no override, to no avail unfortunately.
I'll try again, as a working install of Debian might suffice, as long as it plays nicely with your edk2 porting.
I will report back, with debug logs.
🙏🙏🙏🙏🙏🙏

**Comment by mariobalanica** [comment]
There's a chance the DTB I added for this board is not really suitable, though I compiled it from the Armbian source and I recall it's a bit newer than the one included in amazingfate's image.

You could try fixing the grub script in that image to load its included DTB instead of the firmware provided one.
v0.9 dropped the `.dtb` prefix in the reported name, so it's just a matter of appending the extension back to the `devicetree` command.

**Comment by mariobalanica** [comment]
Well, yeah, you can also override the DTB like this: https://github.com/edk2-porting/edk2-rk3588?tab=readme-ov-file#device-tree-configuration

Just move the DTB from the Armbian image to the correct location described above.

> even if I wouldn't worry about the DTB...they are kernel agnostic, aren't they?

The only difference between v0.8 and v0.9 is that Armbian cannot find and use its own DTB anymore. With the firmware one enabled, you said most peripherals aren't working. So this leads me to believe the included DTB for this board is not good.

However, I tested the same image on Indiedroid Nova and OPi 5+ and everything was fine. They all come from the same [Armbian kernel commit](https://github.com/armbian/linux-rockchip/tree/a8384552a2e009797aa5b3e9a046d30e8d2e5d3c/arch/arm64/boot/dts/rockchip), so not sure what's wrong with NanoPC.

They are kernel specific. The firmware provided DTB is only compatible with the Rockchip 5.10 legacy kernel, anything newer/older is likely to cause issues.

**Comment by brightplastik** [comment]
> Well, yeah, you can also override the DTB like this: https://github.com/edk2-porting/edk2-rk3588?tab=readme-ov-file#device-tree-configuration

> They are kernel specific. The firmware provided DTB is only compatible with the Rockchip 5.10 legacy kernel, anything newer/older is likely to cause issues.

I understand Mario.
Then, since everything is in place, and should work as the Debian os is based on rockchip legacy DTB, the only thing I can try to see if it gets recognized is to remove the .dtb extension from `\dtb\base\` files and see if they get loaded by the firmware.
Will report, as usual.

**Comment by mariobalanica** [comment]
No, the file under \dtb\base must have the .dtb extension. What I meant is that the DTB filename read by Grub from the firmware no longer has the .dtb extension, while the Armbian script expects it to be there.

So, you can either patch that Grub script to append the .dtb extension, or use the firmware DTB override facility. I recommend doing the latter, but either will work.

**Comment by brightplastik** [comment]
Then, adding override in UEFI settings and putting all the files in the indicated folder structure does not work, unfortunately.
Maybe it's just something with the naming scheme that is wrong.
Will check.
I will succeed, for Christ sake.

**Comment by mariobalanica** [comment]
What do the serial logs say?

**Comment by brightplastik** [comment]
The logs get cleared when the booting change environment. Namely, two times: 
`UEFI, GRUB `
and then `OS load`.

I was able to grab these:

### UEFI and GRUB environment:

[T6 edk2 debug 0.9.1 - UEFI and GRUB.txt](https://github.com/edk2-porting/edk2-rk3588/files/14318830/UEFI.and.GRUB.txt)

_Note I had to shut the power to copy this log, so it might be incomplete._

### Booting of the debian OS:

[T6 edk2 debug 0.9.1 - OS loading.txt](https://github.com/edk2-porting/edk2-rk3588/files/14318832/T6.edk2.debug.0.9.1.-.OS.loading.txt)

What sort of info are we looking for in these logs?

**Comment by mariobalanica** [comment]
In the first log, I can't see the firmware DTB being overridden. Have you placed it in the correct location?

> On a different take, if I wanted to run some commands from the UEFI shell, what should I try to launch?
The UEFI shell is available as a separate option in the boot menu.

**Comment by brightplastik** [comment]
Ok, I'm ufficially a noob.
Banging my head since days on how to reliably copy amazingfate's DTBs and DTBOs in `/boot/EFI/dtb` folder, since the partition is mounted read-only.
I thought I managed it, but clearly I didn't, since I cannot even see if there are the files I'm expecting to find there. I only see there is `/base`.
Such a noob.
What should I do to earn superpowers and freely copy and paste?
`chown root '/boot/EFI/dtb/'` does not work, apparently.
Such a miserable noob, slowing down all development. Uff.
Sorry.

**Comment by mariobalanica** [comment]
It's okay, don't be so hard on yourself.

For the override to work in UEFI, you need to copy the DTB from Armbian to `/mnt/dtb/base/rk3588-nanopc-t6.dtb` (assuming `/mnt` is the root of the first FAT32 partition).

Try mounting it like this: `mount -t vfat  /dev/sda2 /media/bigdrive -o rw,umask=0000`

**Comment by brightplastik** [comment]
Will try that, Mario.
Thanks, really.
Will report!

**Comment by brightplastik** [comment]
`root@proxmox:/home/gabo# mount -t vfat /dev/mmcblk0p1 /mnt/efi -o rw,umask=0000`

`root@proxmox:/home/gabo# ls /mnt/efi/dtb
base  overlays`

`root@proxmox:/home/gabo# cp -r /dtb/base/ /mnt/efi/dtb/base
cp: cannot stat '/mnt/efi/dtb/base': Input/output error`

`root@proxmox:/home/gabo# rm -rf /mnt/efi/dtb
rm: cannot remove '/mnt/efi/dtb/base': Read-only file system
rm: cannot remove '/mnt/efi/dtb/overlays': Read-only file system`

If only the eMMC was removable, I would have modified it with some resquezilla live OS or similar, instead of failing recursively.
Is there an EFI loader like on OSX?

**Comment by amazingfate** [comment]
> There's a chance the DTB I added for this board is not really suitable, though I compiled it from the Armbian source and I recall it's a bit newer than the one included in amazingfate's image.
> 
> You could try fixing the grub script in that image to load its included DTB instead of the firmware provided one. v0.9 dropped the `.dtb` suffix in the reported name, so it's just a matter of appending the extension back to the `devicetree` command.

Just tested v0.9.1 on h88k with my iso. It seems that removing `.dtb` in devicetree command of grub will still load the correct devicetree. And my iso is still working.

**Comment by brightplastik** [comment]
Thank you very much both, @mariobalanica and @amazingfate ...mainly for the patience, since I'm no genius here.

So, till now the only way I was able to boot either a new live iso, or the armbian installed OS, was to manually change the code in GRUB. The following works **either with dtb override or not**, in UEFI settings.

I had to change the default logic from Liu's work to this:
`smbios -t 11 -s 4 --set=devicetreename
if [ -f /boot/dtb/rockchip/\rk3588-nanopc-t6.dtb ];then
	devicetree /boot/dtb/rockchip/\rk3588-nanopc-t6.dtb`

Now, I'm too ignorant to understand why, but I guess something with the grammar behind the `$devicetree` logic **does not work correctly**, specifically for the T6.
If you know ways to verify this misbehaviour, please tell me the commands and actions to do, and I'll do my best to replicate.
Again, no genius here, but more than willing to help to iron out the support for all platforms.

Sidenote, not particularly interesting for you but maybe useful to others:
I'm using jiangcuo's script to transform armbian to proxmox, so I had to make the above changes to `/etc/grub.d/10_linux`, then `sudo update-grub` and then run `proxmox-boot-tool refresh`.
So now it loads automatically on boot.

**Comment by amazingfate** [comment]
I just tested new live iso and it won't boot by default. I just fixed the grub command with new devicetree name of EDK2 firmware. Hope new live iso will work.

**Comment by brightplastik** [comment]
> Hope new live iso will work.

EUREKA! IT WORKS! 🤪

**Comment by amazingfate** [comment]
> Hrm I wonder if this is related to emmc/sdhci issues on the rk3588 - I have had no luck with getting emmc accessible in a usable format on my nanopc-t6's (non lts, but with spi/256gb nand)
> 
> ```[59130.530852] blk_print_req_error: 10 callbacks suppressed
> [59130.530865] I/O error, dev mmcblk0, sector 69 op 0x0:(READ) flags 0x800 phys_seg 8 prio class 0
> [59130.531022] I/O error, dev mmcblk0, sector 70 op 0x0:(READ) flags 0x800 phys_seg 8 prio class 0
> [59130.533555] I/O error, dev mmcblk0, sector 87 op 0x0:(READ) flags 0x800 phys_seg 6 prio class 0
> [59130.536885] I/O error, dev mmcblk0, sector 110 op 0x0:(READ) flags 0x800 phys_seg 3 prio class 0
> [59130.537545] I/O error, dev mmcblk0, sector 114 op 0x0:(READ) flags 0x800 phys_seg 2 prio class 0
> [59130.609029] I/O error, dev mmcblk0, sector 69 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 2
> [59130.609160] I/O error, dev mmcblk0, sector 70 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 2
> [59130.619966] I/O error, dev mmcblk0, sector 114 op 0x0:(READ) flags 0x80700 phys_seg 3 prio class 2
> [59130.622100] I/O error, dev mmcblk0, sector 131 op 0x0:(READ) flags 0x80700 phys_seg 2 prio class 2
> [59130.624047] I/O error, dev mmcblk0, sector 148 op 0x0:(READ) flags 0x80700 phys_seg 2 prio class 2
> [59130.860116] Buffer I/O error on dev mmcblk0, logical block 14, async page read
> [59130.861844] Buffer I/O error on dev mmcblk0, logical block 14, async page read
> [59130.863550] Buffer I/O error on dev mmcblk0, logical block 14, async page read
> ````
> 
> when any io is attempted to the /dev/mmcblk0 ; putting efi images (irrespective of how recent the kernel is) on the internal emmc will lead to reboot cycles. 
> 
> It seems to also get to the point where it will start to degrade access to other media sharing the bus (i.e the sd card), and eventually a ooops and hang. Even when it's just used as storage - from a booted/working install (using rawhide on an sd / openwrt )
> 
> 
> I think this is due to various emmc modules not supporting the highest speed frequency selection on the sdhci controller. The rock5b tree has this fixup added to it;
> 
> https://gitlab.collabora.com/hardware-enablement/rockchip-3588/linux/-/commit/9a236e59ffabd1fff0a69157599bfe3c75dfd6bc#637ff37958a75d1ea15150df6239f2cc9bbc88e4
> 
> 
> 
> 
> 

I have encountered similar issue when testing rock5 itx, so I send a patch upstream to fix it: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=b36402e4a0772d1b3da06a4f5fbd1cfe4d6f1cc0

**Comment by amazingfate** [comment]
> Hrm - I wonder if it's just enough to compile e2dk with a dts overide for the frequency to fix ; this likely affects all rk3588 targets in mainline tho so dropping that frequency for all of the in-tree dts's is probably an idea
> 
> 

It's better to make it board specific. I guess this is limited by board designation.

**Comment by aenertia** [comment]
hrm - it didn't fix it for me just bumping down the freq setting. The collabra / radxa fix also disables the  mmc-hs400-1_8v; in favour of mmc-hs200-1_8v; and removes the enhanced strobe parameter
